include:
  - path: identity-service/compose.yml
  - path: lots-service/compose.yml
  - path: reservations-service/compose.yml
  - path: app-service/compose.yml
  - path: notifications-service/compose.yml

