services:
  availability-forecast-service:
    build:
      context: .
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    volumes:
      - .:/app
